name: Resumen y análisis de nuevos issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ejecutar inferencia con IA
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Analiza el siguiente issue de GitHub y responde en español con:
            1. Un resumen breve del problema planteado.
            2. Qué información adicional sería útil para entender mejor el contexto.
            3. Sugerencias para mejorar la redacción o claridad del issue.
            4. Posibles etiquetas que podrían aplicarse (por ejemplo: documentación, bug, mejora).
            5. Áreas del código que podrían estar relacionadas, si es posible inferirlo.

            Título: ${{ github.event.issue.title }}
            Descripción: ${{ github.event.issue.body }}

      - name: Comentar con el análisis de IA
        run: |
          COMMENT=$(echo "${{ steps.inference.outputs.response }}" | jq -Rs .)
          gh issue comment $ISSUE_NUMBER --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
